sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install tox-travis codecov
script:
  - python --version
  - tox
after_success:
  - coverage report
  - codecov