sudo: false
language: python
python: 3.6-dev
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install tox codecov
script:
  - tox
after_success:
  - coverage report
  - codecov