sudo: false
language: python
python: 3.5
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - coverage report
  - codecov